// Angular/Day1/proj1/src/app/app.ts
import { Component, signal } from '@angular/core';
import { Hero } from './hero/hero';
import { About } from './about/about';
import { Skills } from './skills/skills';
import { Portfolio } from './portfolio/portfolio';
import { Contact } from './contact/contact';
import { Navbar } from './navbar/navbar';
import { Footer } from './footer/footer';

@Component({
  selector: 'app-root',
  imports: [Navbar, Hero, About, Skills, Portfolio, Contact, Footer],
  templateUrl: './app.html',
  styleUrls: ['./app.css'],
})
export class App {}

// Web Development/React/Day1/portfolio/src/App.tsx
import About from './components/About';
import Footer from './components/Footer';
import Header from './components/Header';
import Hero from './components/Hero';
import Portfolio from './components/Portfolio';
import Skills from './components/Skills';

export default function App() {
  return (
    <>
      <Header />
      <Hero />
      <About />
      <Skills />
      <Portfolio />
      <Footer />
    </>
  );
}
